# Generated by Django 2.2.7 on 2019-12-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='encrypted_message',
            field=models.TextField(),
        ),
    ]
